// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://msssgyndepybntfhymdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zc3NneW5kZXB5Ym50Zmh5bWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM3NDIwMDksImV4cCI6MjA3OTMxODAwOX0.BKI8IydWM0RTGHQPIp-NzTUpS1YczlWBSIiX8KBSgR8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Added default export for compatibility with default imports
export default supabase;